[package]
name = "manager"
version = "0.1.0"
authors = ["knox <knoxfighter@asdff45.de>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.7.0-rc.3", features = ["router", "fullstack"] }
dioxus-fullstack = "0.7.0-rc.3"
dioxus-cli-config = "0.7.0-rc.3"
dioxus-primitives = { git = "https://github.com/DioxusLabs/components", version = "0.0.1", default-features = false }

# has to be optional so it is server only
axum = { version = "0.8.4", optional = true }
tokio = { version = "1.47.1", features = ["full"], optional = true }
dotenvy = { version = "0.15.7", optional = true }
diesel = { version = "2.3.2", features = ["sqlite", "returning_clauses_for_sqlite_3_35"], optional = true }
diesel_migrations = { version = "2.3.0", features = ["sqlite"], optional = true }
diesel-async = { version = "0.7.3", features = ["tokio", "sqlite", "sync-connection-wrapper", "bb8", "async-connection-wrapper", "migrations"], optional = true }
libsqlite3-sys = { version = "0.35.0", features = ["bundled"], optional = true }
tower = { version = "0.5.2", features = ["tokio"], optional = true }
tower-http = { version = "0.6.6", features = ["auth", "tokio"], optional = true }
tower-sessions = { version = "0.14.0", features = ["signed"], optional = true }
tower-sessions-core = { version = "0.14.0", features = ["deletion-task"], optional = true }
time = { version = "0.3.44", optional = true }
argon2 = { version = "0.6.0-rc.1", features = ["default", "std"], optional = true }
uuid = { version = "1.18.1", features = ["v4"], optional = true }
rand = { version = "0.10.0-rc.0", optional = true }
thiserror = { version = "2.0.17" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tracing-subscriber = "0.3.20"
factorio-server = { path = "../factorio-server", optional = true }
factorio-version = { path = "../factorio-version" }
clap = { version = "4.5.48", features = ["derive", "env"], optional = true }

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
server = [
    "dioxus/server",
    "axum",
    "tokio",
    "dotenvy",
    "diesel",
    "diesel_migrations",
    "diesel-async",
    "libsqlite3-sys",
    "tower",
    "tower-http",
    "tower-sessions",
    "tower-sessions-core",
    "time",
    "argon2",
    "uuid",
    "rand",
    "factorio-server",
    "clap"
]
